### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by meetgyn** [amustaque97/KnockV3#1]
![image](https://user-images.githubusercontent.com/3695608/107863630-a32e3000-6e34-11eb-926d-149d4e421669.png)

**Comment by amustaque97** [comment]
Hey @meetgyn which python version are you running 2 or 3???

**Comment by meetgyn** [comment]
I tried with both: Python2 and Python3.8

**Comment by amustaque97** [comment]
@meetgyn thank you for the reply. I will fix it before this week.

**Comment by meetgyn** [comment]
Very much thank you, and excuse the nuisance

**Comment by amustaque97** [comment]
Hi @meetgyn , sorry for the delay. I was busy with some work from past few days. I'm not able to reproduce this error locally. Can you please check it again. Thanks 
![Screenshot from 2021-03-13 01-11-02](https://user-images.githubusercontent.com/21127788/110990335-2f326980-8399-11eb-961f-aec81767526f.png)
